# Site settings
title: 'Inside Jinseok'
description: '프로그래밍, 프로젝트 기록, 기술 공유'
baseurl: ''
url: 'https://jjok97.github.io'

# HTML 압축 설정
compress_html:
    clippings: all
    comments: ['<!-- ', ' -->']
    endings: all
    ignore:
        envs: [development]
    blanklines: false
    profile: false
    startings: [html, head, body]

# Google 관련 설정
google_analytics: G-3Y53EETQ1K
google_site_verification: googledb8efee872003ebc

# SEO 관련 설정
lang: ko-KR
timezone: Asia/Seoul

# Author
author:
    name: Jinseok
    url: https://github.com/JJOK97
    email: jsock414@gmail.com

# Social 미디어
social:
    github: JJOK97 # GitHub 사용자명

# Build settings
markdown: kramdown
include:
    - _pages

# Assets
sass:
    sass_dir: _sass
    style: compressed

# Gems
plugins:
    - jekyll-sitemap
    - jekyll-feed
    - jekyll-paginate
    - jekyll-seo-tag
    - jekyll-redirect-from
    - jemoji
    - jekyll-mentions
    - jekyll-include-cache

# Permalinks
permalink: /:year-:month-:day/:title
paginate: 5

# Excludes
exclude: [Gemfile, Gemfile.lock, tale.gemspec]

# 댓글 시스템
# utterances: JJOK97/jjok97.github.io # 댓글 시스템으로 utterances를 사용하려면 주석 해제

# RSS 피드 활성화
feed:
    path: atom.xml
